/*
  Warnings:

  - The values [ART_PLASTIQUES,MEDIAS,MUSEE,ASSAINISSEMENT,PLUVIALE,POTABLE,ECONOMIE,RECYCLAGE,DISTRIBUTION,CONNAISSANCE,INFORMATION,URBAINE] on the enum `SousThematique` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
TRUNCATE "Project" CASCADE;
TRUNCATE "ServiceContext";

CREATE TYPE "SousThematique_new" AS ENUM ('ACTIVITE_ECONOMIQUE_1', 'ACTIVITE_ECONOMIQUE_2', 'ACTIVITE_ECONOMIQUE_3', 'ACTIVITE_ECONOMIQUE_4', 'ACTIVITE_ECONOMIQUE_5', 'ACTIVITE_ECONOMIQUE_6', 'ACTIVITE_ECONOMIQUE_7', 'ACTIVITE_ECONOMIQUE_8', 'ACTIVITE_ECONOMIQUE_9', 'ACTIVITE_ECONOMIQUE_10', 'ACTIVITE_ECONOMIQUE_11', 'ACTIVITE_ECONOMIQUE_12', 'ACTIVITE_ECONOMIQUE_13', 'ACTIVITE_ECONOMIQUE_14', 'EAU_1', 'EAU_2', 'EAU_3', 'EAU_4', 'EAU_5', 'EAU_6', 'ADAPTATION_1', 'ADAPTATION_2', 'ADAPTATION_3', 'ADAPTATION_4', 'ADAPTATION_5', 'ENERGIE_1', 'ENERGIE_2', 'ENERGIE_3', 'ENERGIE_4', 'ENERGIE_5', 'ENERGIE_6', 'ECONOMIE_CIRCULAIRE_1', 'ECONOMIE_CIRCULAIRE_2', 'ECONOMIE_CIRCULAIRE_3', 'ECONOMIE_CIRCULAIRE_4', 'ECONOMIE_CIRCULAIRE_5', 'ECONOMIE_CIRCULAIRE_6', 'MOBILITE_1', 'MOBILITE_2', 'MOBILITE_3', 'MOBILITE_4', 'MOBILITE_5', 'MOBILITE_6', 'MOBILITE_7', 'MOBILITE_8', 'MOBILITE_9', 'MOBILITE_10', 'NATURE_1', 'NATURE_2', 'NATURE_3', 'NATURE_4', 'NATURE_5', 'NATURE_6', 'NATURE_7', 'NATURE_8', 'NATURE_9', 'NATURE_10', 'URBANISME_1', 'URBANISME_2', 'URBANISME_3', 'URBANISME_4', 'URBANISME_5', 'URBANISME_6', 'URBANISME_7', 'URBANISME_8', 'URBANISME_9', 'URBANISME_10', 'URBANISME_11', 'URBANISME_12', 'URBANISME_13', 'URBANISME_14', 'SENSIBILISATION_1', 'SENSIBILISATION_2', 'SENSIBILISATION_3', 'SENSIBILISATION_4', 'SENSIBILISATION_5', 'AGRICULTURE_1', 'AGRICULTURE_2', 'AGRICULTURE_3', 'AGRICULTURE_4', 'AGRICULTURE_5', 'AGRICULTURE_6', 'CULTURE_1', 'CULTURE_2', 'CULTURE_3', 'CULTURE_4', 'CULTURE_5', 'CULTURE_6', 'CULTURE_7', 'CULTURE_8', 'STRATEGIE_1', 'STRATEGIE_2', 'STRATEGIE_3', 'STRATEGIE_4', 'STRATEGIE_5', 'STRATEGIE_6', 'STRATEGIE_7', 'STRATEGIE_8', 'STRATEGIE_9', 'SOLIDARITE_1', 'SOLIDARITE_2', 'SOLIDARITE_3', 'SOLIDARITE_4', 'SOLIDARITE_5', 'SOLIDARITE_6', 'SOLIDARITE_7', 'SOLIDARITE_8', 'SOLIDARITE_9', 'SOLIDARITE_10', 'SOLIDARITE_11', 'SOLIDARITE_12', 'SOLIDARITE_13', 'SOLIDARITE_14', 'SOLIDARITE_15');
ALTER TABLE "Project" ALTER COLUMN "sousThematiques" TYPE "SousThematique_new"[] USING ("sousThematiques"::text::"SousThematique_new"[]);
ALTER TABLE "ServiceContext" ALTER COLUMN "sousThematiques" TYPE "SousThematique_new"[] USING ("sousThematiques"::text::"SousThematique_new"[]);
ALTER TYPE "SousThematique" RENAME TO "SousThematique_old";
ALTER TYPE "SousThematique_new" RENAME TO "SousThematique";
DROP TYPE "SousThematique_old";
COMMIT;

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "Thematique" ADD VALUE 'ACTIVITE_ECONOMIQUE';
ALTER TYPE "Thematique" ADD VALUE 'ADAPTATION';
ALTER TYPE "Thematique" ADD VALUE 'ECONOMIE_CIRCULAIRE';
ALTER TYPE "Thematique" ADD VALUE 'NATURE';
ALTER TYPE "Thematique" ADD VALUE 'URBANISME';
ALTER TYPE "Thematique" ADD VALUE 'SENSIBILISATION';
ALTER TYPE "Thematique" ADD VALUE 'AGRICULTURE';
ALTER TYPE "Thematique" ADD VALUE 'STRATEGIE';
ALTER TYPE "Thematique" ADD VALUE 'SOLIDARITE';
