import { SousThematique, Thematique } from "@prisma/client";

export const thematiquesLabel: Record<Thematique, string> = {
  ACTIVITE_ECONOMIQUE: "Activités économiques",
  EAU: "Eau, milieux aquatiques et assainissement",
  ADAPTATION: "Adaptation",
  ENERGIE: "Énergie et climat",
  ECONOMIE_CIRCULAIRE: "Économie circulaire et déchets",
  MOBILITE: "Mobilité / transports",
  NATURE: "Nature, Environnement, Air",
  URBANISME: "Urbanisme, Logement, Aménagement, Bâtiments",
  SENSIBILISATION: "Sensibilisation, communication et accompagnement au changement",
  AGRICULTURE: "Agriculture et Alimentation",
  CULTURE: "Culture et identité collective / patrimoine / sports",
  STRATEGIE: "Stratégie, organisation, valorisation",
  SOLIDARITE: "Solidarités / lien social",
};

export const sousThematiquesInfo: Record<
  SousThematique,
  {
    label: string;
    thematiques: Thematique[];
  }
> = {
  ACTIVITE_ECONOMIQUE_1: { label: "Agriculture et agroalimentaire", thematiques: [Thematique.ACTIVITE_ECONOMIQUE] },
  ACTIVITE_ECONOMIQUE_2: { label: "Artisanat", thematiques: [Thematique.ACTIVITE_ECONOMIQUE] },
  ACTIVITE_ECONOMIQUE_3: { label: "Commerces et services", thematiques: [Thematique.ACTIVITE_ECONOMIQUE] },
  ACTIVITE_ECONOMIQUE_4: { label: "Consommation et production", thematiques: [Thematique.ACTIVITE_ECONOMIQUE] },
  ACTIVITE_ECONOMIQUE_5: { label: "Economie locale et circuits courts", thematiques: [Thematique.ACTIVITE_ECONOMIQUE] },
  ACTIVITE_ECONOMIQUE_6: { label: "Economie sociale et solidaire", thematiques: [Thematique.ACTIVITE_ECONOMIQUE] },
  ACTIVITE_ECONOMIQUE_7: { label: "Emploi", thematiques: [Thematique.ACTIVITE_ECONOMIQUE] },
  ACTIVITE_ECONOMIQUE_8: { label: "Fiscalité des entreprises", thematiques: [Thematique.ACTIVITE_ECONOMIQUE] },
  ACTIVITE_ECONOMIQUE_9: { label: "Formation professionnelle", thematiques: [Thematique.ACTIVITE_ECONOMIQUE] },
  ACTIVITE_ECONOMIQUE_10: { label: "Industrie", thematiques: [Thematique.ACTIVITE_ECONOMIQUE] },
  ACTIVITE_ECONOMIQUE_11: {
    label: "Innovation créativité et recherche",
    thematiques: [Thematique.ACTIVITE_ECONOMIQUE],
  },
  ACTIVITE_ECONOMIQUE_12: {
    label: "Technologies numériques et numérisation",
    thematiques: [Thematique.ACTIVITE_ECONOMIQUE],
  },
  ACTIVITE_ECONOMIQUE_13: { label: "Tiers-lieux", thematiques: [Thematique.ACTIVITE_ECONOMIQUE] },
  ACTIVITE_ECONOMIQUE_14: { label: "Tourisme", thematiques: [Thematique.ACTIVITE_ECONOMIQUE] },

  EAU_1: { label: "Assainissement des eaux", thematiques: [Thematique.EAU] },
  EAU_2: { label: "Cours d'eau / canaux / plans d'eau", thematiques: [Thematique.EAU] },
  EAU_3: { label: "Eau pluviale", thematiques: [Thematique.EAU] },
  EAU_4: { label: "Eau potable", thematiques: [Thematique.EAU] },
  EAU_5: { label: "Eau souterraine", thematiques: [Thematique.EAU] },
  EAU_6: { label: "Mers et océans", thematiques: [Thematique.EAU] },

  ADAPTATION_1: { label: "Inconfort thermique", thematiques: [Thematique.ADAPTATION] },
  ADAPTATION_2: { label: "Aménagement", thematiques: [Thematique.ADAPTATION] },
  ADAPTATION_3: { label: "Biodiversité", thematiques: [Thematique.ADAPTATION] },
  ADAPTATION_4: { label: "Ressources en eau", thematiques: [Thematique.ADAPTATION] },
  ADAPTATION_5: { label: "Espaces naturels", thematiques: [Thematique.ADAPTATION] },

  ENERGIE_1: { label: "Développement des énergies renouvelables", thematiques: [Thematique.ENERGIE] },
  ENERGIE_2: { label: "Distribution de l’énergie", thematiques: [Thematique.ENERGIE] },
  ENERGIE_3: { label: "Efficacité énergétique", thematiques: [Thematique.ENERGIE] },
  ENERGIE_4: { label: "Rénovation énergétique", thematiques: [Thematique.ENERGIE] },
  ENERGIE_5: { label: "Sobriété énergétique", thematiques: [Thematique.ENERGIE] },
  ENERGIE_6: { label: "Réseaux de chaleur", thematiques: [Thematique.ENERGIE] },

  ECONOMIE_CIRCULAIRE_1: { label: "Allongement de la durée d’usage", thematiques: [Thematique.ECONOMIE_CIRCULAIRE] },
  ECONOMIE_CIRCULAIRE_2: {
    label: "Consommation responsable et achats durables",
    thematiques: [Thematique.ECONOMIE_CIRCULAIRE],
  },
  ECONOMIE_CIRCULAIRE_3: { label: "Eco-conception", thematiques: [Thematique.ECONOMIE_CIRCULAIRE] },
  ECONOMIE_CIRCULAIRE_4: {
    label: "Ecologie industrielle et territoriale",
    thematiques: [Thematique.ECONOMIE_CIRCULAIRE],
  },
  ECONOMIE_CIRCULAIRE_5: { label: "Gestion des déchets : collecte", thematiques: [Thematique.ECONOMIE_CIRCULAIRE] },
  ECONOMIE_CIRCULAIRE_6: {
    label: "Gestion des déchets : Recyclage et valorisation",
    thematiques: [Thematique.ECONOMIE_CIRCULAIRE],
  },

  MOBILITE_1: { label: "Connaissance de la mobilité", thematiques: [Thematique.MOBILITE] },
  MOBILITE_2: { label: "Information voyageur billettique multimodale", thematiques: [Thematique.MOBILITE] },
  MOBILITE_3: { label: "Limiter les déplacements subis", thematiques: [Thematique.MOBILITE] },
  MOBILITE_4: { label: "Logistique et transport de marchandises", thematiques: [Thematique.MOBILITE] },
  MOBILITE_5: {
    label: "Systèmes de transports intelligents trafics et régulation",
    thematiques: [Thematique.MOBILITE],
  },
  MOBILITE_6: { label: "Mobilité fluviale", thematiques: [Thematique.MOBILITE] },
  MOBILITE_7: { label: "Mobilité partagée", thematiques: [Thematique.MOBILITE] },
  MOBILITE_8: { label: "Mobilité solidaire et inclusive", thematiques: [Thematique.MOBILITE] },
  MOBILITE_9: { label: "Modes actifs : vélo marche et aménagements associés", thematiques: [Thematique.MOBILITE] },
  MOBILITE_10: { label: "Transports collectifs et intermodalité", thematiques: [Thematique.MOBILITE] },

  NATURE_1: { label: "Biodiversité", thematiques: [Thematique.NATURE] },
  NATURE_2: { label: "Forêts", thematiques: [Thematique.NATURE] },
  NATURE_3: { label: "Milieux humides", thematiques: [Thematique.NATURE] },
  NATURE_4: { label: "Montagne", thematiques: [Thematique.NATURE] },
  NATURE_5: { label: "Qualité de l'air", thematiques: [Thematique.NATURE] },
  NATURE_6: { label: "Risques naturels", thematiques: [Thematique.NATURE] },
  NATURE_7: { label: "Sols", thematiques: [Thematique.NATURE] },
  NATURE_8: { label: "Littoral", thematiques: [Thematique.NATURE] },
  NATURE_9: { label: "Réduction des prélèvements en ressources naturelles", thematiques: [Thematique.NATURE] },
  NATURE_10: { label: "Solutions d'adaptation fondées sur la nature (SafN)", thematiques: [Thematique.NATURE] },

  URBANISME_1: { label: "Accessibilité", thematiques: [Thematique.URBANISME] },
  URBANISME_2: { label: "Architecture", thematiques: [Thematique.URBANISME] },
  URBANISME_3: { label: "Bâtiments et construction", thematiques: [Thematique.URBANISME] },
  URBANISME_4: { label: "Cimetières et funéraire", thematiques: [Thematique.URBANISME] },
  URBANISME_5: { label: "Equipement public", thematiques: [Thematique.URBANISME] },
  URBANISME_6: { label: "Espace public", thematiques: [Thematique.URBANISME] },
  URBANISME_7: { label: "Espaces verts", thematiques: [Thematique.URBANISME] },
  URBANISME_8: { label: "Foncier", thematiques: [Thematique.URBANISME] },
  URBANISME_9: { label: "Friche", thematiques: [Thematique.URBANISME] },
  URBANISME_10: { label: "Logement et habitat", thematiques: [Thematique.URBANISME] },
  URBANISME_11: { label: "Paysage", thematiques: [Thematique.URBANISME] },
  URBANISME_12: { label: "Réhabilitation", thematiques: [Thematique.URBANISME] },
  URBANISME_13: { label: "Voirie et réseaux", thematiques: [Thematique.URBANISME] },
  URBANISME_14: { label: "Lutte contre l’artificialisation des sols", thematiques: [Thematique.URBANISME] },

  SENSIBILISATION_1: { label: "Formation", thematiques: [Thematique.SENSIBILISATION] },
  SENSIBILISATION_2: { label: "Sensibilisation", thematiques: [Thematique.SENSIBILISATION] },
  SENSIBILISATION_3: { label: "Information ciblée et communication", thematiques: [Thematique.SENSIBILISATION] },
  SENSIBILISATION_4: { label: "Concertation", thematiques: [Thematique.SENSIBILISATION] },
  SENSIBILISATION_5: { label: "Gamification challenge et défis", thematiques: [Thematique.SENSIBILISATION] },

  AGRICULTURE_1: { label: "Production agricole et foncier", thematiques: [Thematique.AGRICULTURE] },
  AGRICULTURE_2: { label: "Précarité et aide alimentaire", thematiques: [Thematique.AGRICULTURE] },
  AGRICULTURE_3: { label: "Transformation des produits agricoles", thematiques: [Thematique.AGRICULTURE] },
  AGRICULTURE_4: { label: "Consommation alimentaire", thematiques: [Thematique.AGRICULTURE] },
  AGRICULTURE_5: { label: "Distribution", thematiques: [Thematique.AGRICULTURE] },
  AGRICULTURE_6: { label: "Déchets alimentaires et/ou agricoles", thematiques: [Thematique.AGRICULTURE] },

  CULTURE_1: { label: "Arts plastiques et photographie", thematiques: [Thematique.CULTURE] },
  CULTURE_2: { label: "Bibliothèques et livres", thematiques: [Thematique.CULTURE] },
  CULTURE_3: { label: "Culture et identité collective", thematiques: [Thematique.CULTURE] },
  CULTURE_4: { label: "Médias et communication", thematiques: [Thematique.CULTURE] },
  CULTURE_5: { label: "Musée", thematiques: [Thematique.CULTURE] },
  CULTURE_6: { label: "Patrimoine et monuments historiques", thematiques: [Thematique.CULTURE] },
  CULTURE_7: { label: "Spectacle vivant", thematiques: [Thematique.CULTURE] },
  CULTURE_8: { label: "Sports et loisirs", thematiques: [Thematique.CULTURE] },

  STRATEGIE_1: { label: "Animation et mise en réseau", thematiques: [Thematique.STRATEGIE] },
  STRATEGIE_2: { label: "Appui méthodologique", thematiques: [Thematique.STRATEGIE] },
  STRATEGIE_3: { label: "Prévention des risques professionnels", thematiques: [Thematique.STRATEGIE] },
  STRATEGIE_4: { label: "Valorisation d'actions", thematiques: [Thematique.STRATEGIE] },
  STRATEGIE_5: { label: "Exemplarité", thematiques: [Thematique.STRATEGIE] },
  STRATEGIE_6: { label: "Budget et financement", thematiques: [Thematique.STRATEGIE] },
  STRATEGIE_7: { label: "Diagnostic objectifs et stratégie", thematiques: [Thematique.STRATEGIE] },
  STRATEGIE_8: { label: "Partenariat et coopération", thematiques: [Thematique.STRATEGIE] },
  STRATEGIE_9: { label: "Organisation et transversalité interne", thematiques: [Thematique.STRATEGIE] },

  SOLIDARITE_1: { label: "Accès aux services", thematiques: [Thematique.SOLIDARITE] },
  SOLIDARITE_2: { label: "Alimentation", thematiques: [Thematique.SOLIDARITE] },
  SOLIDARITE_3: { label: "Citoyenneté", thematiques: [Thematique.SOLIDARITE] },
  SOLIDARITE_4: { label: "Cohésion sociale et inclusion", thematiques: [Thematique.SOLIDARITE] },
  SOLIDARITE_5: { label: "Education et renforcement des compétences", thematiques: [Thematique.SOLIDARITE] },
  SOLIDARITE_6: { label: "Egalité des chances", thematiques: [Thematique.SOLIDARITE] },
  SOLIDARITE_7: { label: "Famille et enfance", thematiques: [Thematique.SOLIDARITE] },
  SOLIDARITE_8: { label: "Handicap", thematiques: [Thematique.SOLIDARITE] },
  SOLIDARITE_9: { label: "Inclusion numérique", thematiques: [Thematique.SOLIDARITE] },
  SOLIDARITE_10: { label: "Jeunesse", thematiques: [Thematique.SOLIDARITE] },
  SOLIDARITE_11: { label: "Lutte contre la précarité", thematiques: [Thematique.SOLIDARITE] },
  SOLIDARITE_12: { label: "Personnes âgées", thematiques: [Thematique.SOLIDARITE] },
  SOLIDARITE_13: { label: "Protection animale", thematiques: [Thematique.SOLIDARITE] },
  SOLIDARITE_14: { label: "Santé", thematiques: [Thematique.SOLIDARITE] },
  SOLIDARITE_15: { label: "Sécurité", thematiques: [Thematique.SOLIDARITE] },
};
