import { SousThematique, Thematique } from "@prisma/client";

export const thematiquesLabel: Record<Thematique, string> = {
  tet_9: "Stratégie, organisation interne et gouvernance",
  tet_5: "Énergie et climat",
  tet_4: "Économie circulaire et déchets",
  tet_10: "Urbanisme, logement, aménagement, bâtiments",
  tet_6: "Mobilité et transport",
  tet_7: "Nature, environnement, air",
  tet_12: "Sensibilisation, communication et accompagnement au changement",
  tet_1: "Activités économiques",
  tet_3: "Eau, milieux aquatiques et assainissement",
  tet_8: "Solidarité et lien social",
  tet_11: "Agriculture et alimentation",
  tet_2: "Culture, identité collective, sport",
  recoco_267: "La marche à suivre",
  recoco_83: "Qui contacter",
  recoco_329: "Patrimoine",
  recoco_58: "Limitation de tonnage",
  recoco_480: "Rénovation énergétique",
  recoco_277: "Pont limitrophe",
  recoco_356: "Tourisme",
  recoco_452: "Arrondissement carcassonne",
  recoco_447: "Arrondissement limoux",
  recoco_432: "Transition écologique",
  recoco_67: "Les financements",
  recoco_72: "Affouillement",
  recoco_434: "Adhérent cerema",
  recoco_504: "Logement habitat",
  recoco_35: "Surveillance",
  recoco_521: "Equipement public",
  recoco_299: "Assistance à maîtrise d'ouvrage",
  recoco_73: "Passerelle",
  recoco_130: "Renaturation",
  recoco_390: "Réhabilitation bâtiment",
  recoco_276: "Entretien",
  recoco_451: "Arrondissement narbonne",
  recoco_272: "Loi didier",
  recoco_294: "Mesures de sécurité immédiates",
  recoco_454: "Espaces publics",
  recoco_498: "Culture",
  recoco_328: "Cadre de vie",
  recoco_139: "Retours d'expérience",
  recoco_330: "Diagnostic",
  recoco_289: "Maîtrise d'œuvre",
  recoco_369: "Commerce",
  recoco_264: "Gestion",
  recoco_493: "Tiers lieu",
  recoco_363: "Services",
  recoco_293: "Évaluation",
  recoco_71: "Loi sur l'eau",
  recoco_275: "Juridique",
  recoco_430: "Pnp travaux",
  recoco_483: "Sport",
  recoco_287: "Domanialité",
  recoco_357: "Logements",
  recoco_409: "Réhabilition de logements",
  recoco_303: "Végétation",
  recoco_505: "Commerce rural",
  recoco_296: "Réglementation",
  recoco_355: "Aménagement du centre-bourg",
  recoco_460: "Développement économique",
  recoco_178: "Programmation",
  recoco_523: "Transition énergétique",
  recoco_378: "Drac",
  recoco_494: "Energies renouvelables",
  recoco_297: "Sncf",
  recoco_304: "Vnf",
  recoco_283: "Financement",
  recoco_465: "Corrosion",
  recoco_366: "Rénovation bat publics",
  recoco_95: "Maîtrise foncière",
  recoco_478: "Mobilité",
  recoco_8: "Suivi de la mise en oeuvre, concertation",
  recoco_298: "Patrimoine",
  recoco_7: "Opérationnalité (travaux)",
  recoco_318: "Études préalables",
  recoco_169: "Recherche porteurs de projet",
  recoco_300: "Démolition",
  recoco_508: "Rénovation thermique",
  recoco_193: "Urbanisme transitoire",
  recoco_428: "Capacité portante",
  recoco_306: "Recensement",
  recoco_408: "Aménagement parking voie verte",
  recoco_401: "Aménagement de l'espace",
  recoco_458: "Biodiversité",
  recoco_522: "Alimentation",
  recoco_284: "Ingénierie",
  recoco_273: "Responsabilité",
  recoco_87: "Tonnage",
  recoco_403: "Voirie",
  recoco_5: "Définition stratégie d’aménagement du territoire aboutir au schéma directeur de l’eq",
  recoco_429: "Pnp2",
  recoco_359: "Rénovation énergétique écoles",
  recoco_463: "Rénovation monument de culte",
  recoco_290: "Construction",
  recoco_457: "Economie",
  recoco_271: "Renaturation",
  recoco_26: "Amo",
  recoco_210: "Artisanat",
  recoco_474: "Contre-expertise",
  recoco_484: "Economie d'énergie",
  recoco_358: "Enfance petite enfance jeunesse",
  recoco_321: "Risque de ruissellement",
  recoco_281: "Evaluation",
  recoco_543: "Sécurisation/voirie",
  recoco_295: "Passage à gué",
  recoco_212: "Patrimoine",
  recoco_411: "Personnes agées",
  recoco_422: "Changement de matériaux",
  recoco_10: "Réinterroger l'avp",
  recoco_370: "Centralité",
  recoco_404: "Création pôle santé",
  recoco_535: "Démocratie participative",
  recoco_473: "Contentieux",
  recoco_420: "Législation chemin de randonnée",
  recoco_6: "Outils d’aménagement souhaitables à mettre en place",
  recoco_488: "Testtest",
  recoco_222: "Audit énergétique",
  recoco_209: "Inventaire friche",
  recoco_79: "Conventionnement",
  recoco_439: "Maj au début des mots",
  recoco_291: "Avis",
  recoco_27: "Élaboration de scénarios",
  recoco_322: "Désimperméabilisation",
  recoco_433: "Création multicommerce",
  recoco_514: "Sport/loisirs",
  recoco_525: "Piétonnisation",
  recoco_314: "Auberge",
  recoco_502: "Locaux professionnel",
  recoco_520: "Aménagement",
  recoco_274: "Accessibilté",
  recoco_365: "Aménagement du bourg",
  recoco_438: "Que des majuscules",
  recoco_280: "Gouvernance",
  recoco_402: "Transport",
  recoco_455: "Planification écologique",
  recoco_17: "Sujet suivant",
  recoco_9: "Outils d’aménagement souhaitables à mettre en place  ertation",
  recoco_13: "Proposer des indicateurs d'évaluation et de durabilité",
  recoco_540: "Boulanger",
  recoco_315: "Coworking",
  recoco_456: "Programme national travaux",
  recoco_509: "Santé",
  recoco_387: "Participation des habitants",
  recoco_479: "Rénovation",
  recoco_415: "Rénovation de la halle existante",
  recoco_526: "Attractivité",
  recoco_482: "Réhabiliation",
  recoco_379: "Cahier des charges",
  recoco_539: "Moulin",
  recoco_431: "Charge admissible",
  recoco_324: "Gestion des flux touristiques",
  recoco_471: "Protection cathodique",
  recoco_443: "Chaleur renouvelable",
  recoco_15: "Solliciter un accompagnement sur mesure auprès de l'anct",
  recoco_367: "Vacances bat sncf",
  recoco_530: "Musée",
  recoco_354: "Résidence autonomie",
  recoco_332: "Mise en sécurité",
  recoco_491: "Demande en cours pnp travaux",
  recoco_487: "Ecologie",
  recoco_313: "Café",
  recoco_501: "Habitat",
  recoco_312: "Truc",
  recoco_475: "Scénario",
  recoco_513: "Monument historique",
  recoco_25: "Travaux",
  recoco_323: "Mobilité active",
  recoco_519: "Habitat inclusif",
  recoco_497: "Visite effectuée par le cerema",
  recoco_445: "Amenagement du centre bourg",
  recoco_288: "Méthodologie",
  recoco_292: "Chiffrage",
  recoco_529: "Revitalisation",
  recoco_444: "Ingénierie publique",
  recoco_14: "Etat détaillé de chaque véhicule du parc automobile",
  recoco_536: "Pvd",
  recoco_481: "Developpement économique",
  recoco_16: "Test sujet",
  recoco_528: "Stratégie globale",
  recoco_11: "Mettre à jour et affiner le bilan financier de l'opération",
  recoco_301: "Edf",
  recoco_12: "Apporter une méthodologie sur la concertation avec la population",
  recoco_327: "Réhabilitation foncier",
  recoco_343: "Construction d'un gymnase",
  recoco_302: "Retour d'expérience",
  recoco_364: "Rénovation groupe scolaire",
  recoco_527: "Développement",
  recoco_351: "Maison intergénérationnelle",
  recoco_213: "Concertation",
  recoco_503: "Recyclage foncier",
  recoco_307: "Concessionnaires réseaux",
  recoco_476: "Etude de faisabilité",
  recoco_472: "Etanchéité"
};

export const sousThematiquesInfo: Record<
  SousThematique,
  {
    label: string;
    thematiques: Thematique[];
  }
> = {
  tet_33: {
    label: "Gestion des déchets : recyclage, réemploi, valorisation des déchets",
    thematiques: [Thematique.tet_4]
  },
  tet_37: { label: "Développement des énergies renouvelables", thematiques: [Thematique.tet_5] },
  tet_55: { label: "Biodiversité", thematiques: [Thematique.tet_7] },
  tet_28: { label: "Consommation responsable et achats durables", thematiques: [Thematique.tet_4] },
  tet_40: {
    label: "Gestion de l’énergie : maîtrise et réduction des consommations énergétiques",
    thematiques: [Thematique.tet_5]
  },
  tet_53: { label: "Modes actifs (vélo, marche)", thematiques: [Thematique.tet_6] },
  tet_39: { label: "Efficacité énergétique", thematiques: [Thematique.tet_5] },
  tet_44: { label: "Sobriété énergétique", thematiques: [Thematique.tet_5] },
  tet_41: { label: "Réduction des émissions de gaz à effet de serre", thematiques: [Thematique.tet_5] },
  tet_36: { label: "Adaptation au changement climatique", thematiques: [Thematique.tet_5] },
  tet_82: { label: "Organisation et transversalité interne", thematiques: [Thematique.tet_9] },
  tet_95: { label: "Logement et habitat", thematiques: [Thematique.tet_10] },
  tet_42: { label: "Rénovation énergétique", thematiques: [Thematique.tet_5] },
  tet_88: { label: "Bâtiments et construction", thematiques: [Thematique.tet_10] },
  tet_124: { label: "Sensibilisation", thematiques: [Thematique.tet_12] },
  tet_32: { label: "Gestion des déchets : collecte", thematiques: [Thematique.tet_4] },
  tet_104: { label: "Prévention des déchets", thematiques: [Thematique.tet_4] },
  tet_27: { label: "Allongement de la durée d’usage", thematiques: [Thematique.tet_4] },
  tet_77: { label: "Animation et mise en réseau", thematiques: [Thematique.tet_9] },
  tet_81: { label: "Diagnostic, objectifs et stratégie", thematiques: [Thematique.tet_9] },
  tet_90: { label: "Equipement public", thematiques: [Thematique.tet_10] },
  tet_83: {
    label: "Partenariats et coopération (publique, privé, associatif, international, infra et supra collectivité)",
    thematiques: [Thematique.tet_9]
  },
  tet_51: { label: "Mobilité partagée", thematiques: [Thematique.tet_6] },
  tet_54: { label: "Transports collectifs et intermodalité", thematiques: [Thematique.tet_6] },
  tet_122: { label: "Information ciblée et communication", thematiques: [Thematique.tet_12] },
  tet_45: { label: "Connaissance de la mobilité", thematiques: [Thematique.tet_6] },
  tet_23: { label: "Eau de pluie", thematiques: [Thematique.tet_3] },
  tet_59: { label: "Qualité de l’air", thematiques: [Thematique.tet_7] },
  tet_85: { label: "Valorisation d’actions", thematiques: [Thematique.tet_9] },
  tet_24: { label: "Eau potable", thematiques: [Thematique.tet_3] },
  tet_62: { label: "Solutions d’adaptation fondées sur la nature", thematiques: [Thematique.tet_7] },
  tet_5: { label: "Economie locale et circuits courts", thematiques: [Thematique.tet_1] },
  tet_30: { label: "Écologie industrielle et territoriale", thematiques: [Thematique.tet_4] },
  tet_91: { label: "Espace public", thematiques: [Thematique.tet_10] },
  tet_3: { label: "Attractivité et revitalisation économique", thematiques: [Thematique.tet_1] },
  tet_35: { label: "Production responsable", thematiques: [Thematique.tet_4] },
  tet_97: { label: "Réhabilitation", thematiques: [Thematique.tet_10] },
  tet_79: { label: "Budget et financement", thematiques: [Thematique.tet_9] },
  tet_22: { label: "Cours d’eau, canaux, plans d’eau", thematiques: [Thematique.tet_3] },
  tet_78: { label: "Appui méthodologique", thematiques: [Thematique.tet_9] },
  tet_29: { label: "Éco-conception", thematiques: [Thematique.tet_4] },
  tet_34: { label: "Innovation, créativité et recherche", thematiques: [Thematique.tet_4] },
  tet_52: { label: "Mobilité solidaire et inclusive", thematiques: [Thematique.tet_6] },
  tet_38: { label: "Distribution de l’énergie", thematiques: [Thematique.tet_5] },
  tet_117: { label: "Exemplarité", thematiques: [Thematique.tet_9] },
  tet_56: { label: "Forêts", thematiques: [Thematique.tet_7] },
  tet_98: { label: "Voirie et réseaux", thematiques: [Thematique.tet_10] },
  tet_31: { label: "Économie de la fonctionnalité", thematiques: [Thematique.tet_4] },
  tet_21: { label: "Assainissement des eaux", thematiques: [Thematique.tet_3] },
  tet_4: { label: "Commerces et services", thematiques: [Thematique.tet_1] },
  tet_93: { label: "Foncier", thematiques: [Thematique.tet_10] },
  tet_107: { label: "Production agricole et foncier", thematiques: [Thematique.tet_11] },
  tet_119: { label: "Accompagnement personnalisé", thematiques: [Thematique.tet_12] },
  tet_43: { label: "Réseaux de chaleur", thematiques: [Thematique.tet_5] },
  tet_57: { label: "Milieux humides", thematiques: [Thematique.tet_7] },
  tet_61: { label: "Qualité des sols", thematiques: [Thematique.tet_7] },
  tet_65: { label: "Cohésion sociale et inclusion", thematiques: [Thematique.tet_8] },
  tet_49: { label: "Système de transports intelligents, trafics et régulation", thematiques: [Thematique.tet_6] },
  tet_92: { label: "Espaces verts", thematiques: [Thematique.tet_10] },
  tet_121: { label: "Formation", thematiques: [Thematique.tet_12] },
  tet_72: {
    label: "Lutte contre la précarité des conditions de vie (insécurité alimentaire, précarité énergétique, sanitaire, liée au logement, à la mobilité…)",
    thematiques: [Thematique.tet_8]
  },
  tet_6: { label: "Economie sociale et solidaire", thematiques: [Thematique.tet_1] },
  tet_47: { label: "Limitation des déplacements subis", thematiques: [Thematique.tet_6] },
  tet_2: { label: "Artisanat", thematiques: [Thematique.tet_1] },
  tet_7: { label: "Emploi", thematiques: [Thematique.tet_1] },
  tet_111: { label: "Consommation alimentaire", thematiques: [Thematique.tet_11] },
  tet_25: { label: "Eau souterraine", thematiques: [Thematique.tet_3] },
  tet_96: { label: "Paysage", thematiques: [Thematique.tet_10] },
  tet_48: { label: "Logistique et transport de marchandises", thematiques: [Thematique.tet_6] },
  tet_60: { label: "Risques naturels", thematiques: [Thematique.tet_7] },
  tet_86: { label: "Accessibilité", thematiques: [Thematique.tet_10] },
  tet_63: { label: "Accès aux services", thematiques: [Thematique.tet_8] },
  tet_120: { label: "Concertation", thematiques: [Thematique.tet_12] },
  tet_13: { label: "Tourisme", thematiques: [Thematique.tet_1] },
  tet_87: { label: "Architecture", thematiques: [Thematique.tet_10] },
  tet_10: { label: "Industrie", thematiques: [Thematique.tet_1] },
  tet_9: { label: "Formation professionnelle", thematiques: [Thematique.tet_1] },
  tet_46: { label: "Information voyageur, billettique multimodale", thematiques: [Thematique.tet_6] },
  tet_94: { label: "Friche", thematiques: [Thematique.tet_10] },
  tet_118: { label: "Lutte contre l'artificialisation des sols", thematiques: [Thematique.tet_10] },
  tet_64: { label: "Citoyenneté", thematiques: [Thematique.tet_8] },
  tet_15: { label: "Culture et identité collective", thematiques: [Thematique.tet_2] },
  tet_75: { label: "Santé", thematiques: [Thematique.tet_8] },
  tet_68: { label: "Famille et enfance", thematiques: [Thematique.tet_8] },
  tet_123: { label: "Gamification, challenge et défis", thematiques: [Thematique.tet_12] },
  tet_109: { label: "Distribution", thematiques: [Thematique.tet_11] },
  tet_12: { label: "Tiers-lieux", thematiques: [Thematique.tet_1] },
  tet_20: { label: "Sports et loisirs", thematiques: [Thematique.tet_2] },
  tet_66: { label: "Education et renforcement des compétences", thematiques: [Thematique.tet_8] },
  tet_105: { label: "Artificialisation des sols", thematiques: [Thematique.tet_10] },
  tet_112: { label: "Déchets alimentaires et/ou agricoles", thematiques: [Thematique.tet_11] },
  tet_103: { label: "Réduction des prélèvements en ressources naturelles", thematiques: [Thematique.tet_7] },
  tet_16: { label: "Médias et communication", thematiques: [Thematique.tet_2] },
  tet_108: { label: "Transformation des produits agricoles", thematiques: [Thematique.tet_11] },
  tet_26: { label: "Mers et océans", thematiques: [Thematique.tet_3] },
  tet_18: { label: "Patrimoine et monuments historiques", thematiques: [Thematique.tet_2] },
  tet_19: { label: "Spectacle vivant", thematiques: [Thematique.tet_2] },
  tet_71: { label: "Jeunesse", thematiques: [Thematique.tet_8] },
  tet_69: { label: "Handicap", thematiques: [Thematique.tet_8] },
  tet_11: { label: "Technologies numériques et numérisation", thematiques: [Thematique.tet_1] },
  tet_67: { label: "Egalité des chances", thematiques: [Thematique.tet_8] },
  tet_76: { label: "Sécurité", thematiques: [Thematique.tet_8] },
  tet_70: { label: "Inclusion numérique", thematiques: [Thematique.tet_8] },
  tet_73: { label: "Personnes âgées", thematiques: [Thematique.tet_8] },
  tet_8: { label: "Fiscalité des entreprises", thematiques: [Thematique.tet_1] },
  tet_14: { label: "Bibliothèques et livres", thematiques: [Thematique.tet_2] },
  tet_110: { label: "Précarité et aide alimentaire", thematiques: [Thematique.tet_11] },
  tet_58: { label: "Montagne", thematiques: [Thematique.tet_7] },
  tet_84: { label: "Prévention des risques professionnels", thematiques: [Thematique.tet_9] },
  tet_50: { label: "Mobilité fluviale", thematiques: [Thematique.tet_6] },
  tet_115: { label: "Littoral", thematiques: [Thematique.tet_7] },
  tet_89: { label: "Cimetières et funéraire", thematiques: [Thematique.tet_10] },
  tet_17: { label: "Musée", thematiques: [Thematique.tet_2] }
};
